server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lakik}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      # change to create if you want to migrate your changes to db
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect